
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: gleb
  password: 1234
  host: localhost
  port: 5432

development:
  <<: *default
  database: SampleApp_development


test:
  <<: *default
  database: SampleApp_test
